### ISSUE TITLE
Tool: SRA Toolkt

### ISSUE THREAD

**Issue by jallmer** [joergen7/mirna-discovery#2]
More information at: http://www.ncbi.nlm.nih.gov/books/NBK158900/
32bit version: http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.5.2/decryption.2.4.5-ubuntu32.tar.gz
64bit version: http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.5.2/sratoolkit.2.5.2-ubuntu64.tar.gz
Unpack and put files in bin folder on the path.
Test functionality:
1) Download: http://ftp-trace.ncbi.nlm.nih.gov/sra/refseq/ABCC02
2) run fasta-dump.2.5.2 ABCC02
Output:
Read 78 spots for ABCC02
Written 78 spots for ABCC02

**Comment by canerbagci** [comment]
returning fastq file won't work if in the future if we ever need to deal with paired-end data. I added split-3 option, although it is not doing anything at the moment, we may consider creating a directory for each accession/url and returning a list of fastq files in it.

fastq-dump can also work on accession. we don't have to wget sra files, can just feed it with accessions. but in my experience it is slower.

**Comment by joergen7** [comment]
You probably mean fastq-dump (not fasta-dump).
